spring:
    kafka:
      consumer:
        auto-offset-reset: latest
      bootstrap-servers: kafka-611ec65-shivamsharma-33cd.aivencloud.com:23585
kafka:
  topic:
    qrcode: test
  schema-registry-url: https://avnadmin:xcoo2fxjypf2ys4u@kafka-611ec65-shivamsharma-33cd.aivencloud.com:23588
server:
  port: 8084
