spring:
    kafka:
      consumer:
        auto-offset-reset: latest
      bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
kafka:
  topic:
    qrcode: qrcode-dev-4
  schema-registry-url: http://localhost:8081
server:
  port: 8084
